import axios from 'axios';
import { useEffect } from 'react';
import './App.css';
import { User } from './User';
import { Search } from './Search';
function App() {
  let data = [
    {
      "login": "zoheb",
      "id": 1848707,
      "node_id": "MDQ6VXNlcjE4NDg3MDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1848707?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zoheb",
      "html_url": "https://github.com/zoheb",
      "followers_url": "https://api.github.com/users/zoheb/followers",
      "following_url": "https://api.github.com/users/zoheb/following{/other_user}",
      "gists_url": "https://api.github.com/users/zoheb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zoheb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zoheb/subscriptions",
      "organizations_url": "https://api.github.com/users/zoheb/orgs",
      "repos_url": "https://api.github.com/users/zoheb/repos",
      "events_url": "https://api.github.com/users/zoheb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zoheb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebAbai",
      "id": 23161965,
      "node_id": "MDQ6VXNlcjIzMTYxOTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/23161965?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebAbai",
      "html_url": "https://github.com/ZohebAbai",
      "followers_url": "https://api.github.com/users/ZohebAbai/followers",
      "following_url": "https://api.github.com/users/ZohebAbai/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebAbai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebAbai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebAbai/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebAbai/orgs",
      "repos_url": "https://api.github.com/users/ZohebAbai/repos",
      "events_url": "https://api.github.com/users/ZohebAbai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebAbai/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebMOPO",
      "id": 72716462,
      "node_id": "MDQ6VXNlcjcyNzE2NDYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/72716462?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebMOPO",
      "html_url": "https://github.com/ZohebMOPO",
      "followers_url": "https://api.github.com/users/ZohebMOPO/followers",
      "following_url": "https://api.github.com/users/ZohebMOPO/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebMOPO/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebMOPO/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebMOPO/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebMOPO/orgs",
      "repos_url": "https://api.github.com/users/ZohebMOPO/repos",
      "events_url": "https://api.github.com/users/ZohebMOPO/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebMOPO/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Zobee",
      "id": 9866743,
      "node_id": "MDQ6VXNlcjk4NjY3NDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9866743?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Zobee",
      "html_url": "https://github.com/Zobee",
      "followers_url": "https://api.github.com/users/Zobee/followers",
      "following_url": "https://api.github.com/users/Zobee/following{/other_user}",
      "gists_url": "https://api.github.com/users/Zobee/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Zobee/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Zobee/subscriptions",
      "organizations_url": "https://api.github.com/users/Zobee/orgs",
      "repos_url": "https://api.github.com/users/Zobee/repos",
      "events_url": "https://api.github.com/users/Zobee/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Zobee/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebShaikh",
      "id": 26975142,
      "node_id": "MDQ6VXNlcjI2OTc1MTQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/26975142?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebShaikh",
      "html_url": "https://github.com/ZohebShaikh",
      "followers_url": "https://api.github.com/users/ZohebShaikh/followers",
      "following_url": "https://api.github.com/users/ZohebShaikh/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebShaikh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebShaikh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebShaikh/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebShaikh/orgs",
      "repos_url": "https://api.github.com/users/ZohebShaikh/repos",
      "events_url": "https://api.github.com/users/ZohebShaikh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebShaikh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zoheb391",
      "id": 16187941,
      "node_id": "MDQ6VXNlcjE2MTg3OTQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/16187941?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zoheb391",
      "html_url": "https://github.com/zoheb391",
      "followers_url": "https://api.github.com/users/zoheb391/followers",
      "following_url": "https://api.github.com/users/zoheb391/following{/other_user}",
      "gists_url": "https://api.github.com/users/zoheb391/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zoheb391/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zoheb391/subscriptions",
      "organizations_url": "https://api.github.com/users/zoheb391/orgs",
      "repos_url": "https://api.github.com/users/zoheb391/repos",
      "events_url": "https://api.github.com/users/zoheb391/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zoheb391/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Zoheb-hassan",
      "id": 14791925,
      "node_id": "MDQ6VXNlcjE0NzkxOTI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/14791925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Zoheb-hassan",
      "html_url": "https://github.com/Zoheb-hassan",
      "followers_url": "https://api.github.com/users/Zoheb-hassan/followers",
      "following_url": "https://api.github.com/users/Zoheb-hassan/following{/other_user}",
      "gists_url": "https://api.github.com/users/Zoheb-hassan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Zoheb-hassan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Zoheb-hassan/subscriptions",
      "organizations_url": "https://api.github.com/users/Zoheb-hassan/orgs",
      "repos_url": "https://api.github.com/users/Zoheb-hassan/repos",
      "events_url": "https://api.github.com/users/Zoheb-hassan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Zoheb-hassan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Zoheb0707",
      "id": 26777494,
      "node_id": "MDQ6VXNlcjI2Nzc3NDk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/26777494?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Zoheb0707",
      "html_url": "https://github.com/Zoheb0707",
      "followers_url": "https://api.github.com/users/Zoheb0707/followers",
      "following_url": "https://api.github.com/users/Zoheb0707/following{/other_user}",
      "gists_url": "https://api.github.com/users/Zoheb0707/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Zoheb0707/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Zoheb0707/subscriptions",
      "organizations_url": "https://api.github.com/users/Zoheb0707/orgs",
      "repos_url": "https://api.github.com/users/Zoheb0707/repos",
      "events_url": "https://api.github.com/users/Zoheb0707/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Zoheb0707/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebV",
      "id": 2467346,
      "node_id": "MDQ6VXNlcjI0NjczNDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2467346?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebV",
      "html_url": "https://github.com/ZohebV",
      "followers_url": "https://api.github.com/users/ZohebV/followers",
      "following_url": "https://api.github.com/users/ZohebV/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebV/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebV/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebV/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebV/orgs",
      "repos_url": "https://api.github.com/users/ZohebV/repos",
      "events_url": "https://api.github.com/users/ZohebV/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebV/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "oneknucklehead",
      "id": 75200954,
      "node_id": "MDQ6VXNlcjc1MjAwOTU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/75200954?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oneknucklehead",
      "html_url": "https://github.com/oneknucklehead",
      "followers_url": "https://api.github.com/users/oneknucklehead/followers",
      "following_url": "https://api.github.com/users/oneknucklehead/following{/other_user}",
      "gists_url": "https://api.github.com/users/oneknucklehead/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oneknucklehead/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oneknucklehead/subscriptions",
      "organizations_url": "https://api.github.com/users/oneknucklehead/orgs",
      "repos_url": "https://api.github.com/users/oneknucklehead/repos",
      "events_url": "https://api.github.com/users/oneknucklehead/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oneknucklehead/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zoheballadin",
      "id": 109140390,
      "node_id": "U_kgDOBoFZpg",
      "avatar_url": "https://avatars.githubusercontent.com/u/109140390?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zoheballadin",
      "html_url": "https://github.com/zoheballadin",
      "followers_url": "https://api.github.com/users/zoheballadin/followers",
      "following_url": "https://api.github.com/users/zoheballadin/following{/other_user}",
      "gists_url": "https://api.github.com/users/zoheballadin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zoheballadin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zoheballadin/subscriptions",
      "organizations_url": "https://api.github.com/users/zoheballadin/orgs",
      "repos_url": "https://api.github.com/users/zoheballadin/repos",
      "events_url": "https://api.github.com/users/zoheballadin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zoheballadin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "blackeaglejs",
      "id": 4464570,
      "node_id": "MDQ6VXNlcjQ0NjQ1NzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4464570?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/blackeaglejs",
      "html_url": "https://github.com/blackeaglejs",
      "followers_url": "https://api.github.com/users/blackeaglejs/followers",
      "following_url": "https://api.github.com/users/blackeaglejs/following{/other_user}",
      "gists_url": "https://api.github.com/users/blackeaglejs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/blackeaglejs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/blackeaglejs/subscriptions",
      "organizations_url": "https://api.github.com/users/blackeaglejs/orgs",
      "repos_url": "https://api.github.com/users/blackeaglejs/repos",
      "events_url": "https://api.github.com/users/blackeaglejs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/blackeaglejs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zsumair",
      "id": 3657290,
      "node_id": "MDQ6VXNlcjM2NTcyOTA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3657290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zsumair",
      "html_url": "https://github.com/zsumair",
      "followers_url": "https://api.github.com/users/zsumair/followers",
      "following_url": "https://api.github.com/users/zsumair/following{/other_user}",
      "gists_url": "https://api.github.com/users/zsumair/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zsumair/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zsumair/subscriptions",
      "organizations_url": "https://api.github.com/users/zsumair/orgs",
      "repos_url": "https://api.github.com/users/zsumair/repos",
      "events_url": "https://api.github.com/users/zsumair/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zsumair/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebaziz",
      "id": 56046187,
      "node_id": "MDQ6VXNlcjU2MDQ2MTg3",
      "avatar_url": "https://avatars.githubusercontent.com/u/56046187?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebaziz",
      "html_url": "https://github.com/zohebaziz",
      "followers_url": "https://api.github.com/users/zohebaziz/followers",
      "following_url": "https://api.github.com/users/zohebaziz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebaziz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebaziz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebaziz/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebaziz/orgs",
      "repos_url": "https://api.github.com/users/zohebaziz/repos",
      "events_url": "https://api.github.com/users/zohebaziz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebaziz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebzi",
      "id": 102554873,
      "node_id": "U_kgDOBhzc-Q",
      "avatar_url": "https://avatars.githubusercontent.com/u/102554873?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebzi",
      "html_url": "https://github.com/zohebzi",
      "followers_url": "https://api.github.com/users/zohebzi/followers",
      "following_url": "https://api.github.com/users/zohebzi/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebzi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebzi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebzi/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebzi/orgs",
      "repos_url": "https://api.github.com/users/zohebzi/repos",
      "events_url": "https://api.github.com/users/zohebzi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebzi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ali7979",
      "id": 72189352,
      "node_id": "MDQ6VXNlcjcyMTg5MzUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/72189352?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ali7979",
      "html_url": "https://github.com/ali7979",
      "followers_url": "https://api.github.com/users/ali7979/followers",
      "following_url": "https://api.github.com/users/ali7979/following{/other_user}",
      "gists_url": "https://api.github.com/users/ali7979/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ali7979/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ali7979/subscriptions",
      "organizations_url": "https://api.github.com/users/ali7979/orgs",
      "repos_url": "https://api.github.com/users/ali7979/repos",
      "events_url": "https://api.github.com/users/ali7979/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ali7979/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebtaher",
      "id": 37554840,
      "node_id": "MDQ6VXNlcjM3NTU0ODQw",
      "avatar_url": "https://avatars.githubusercontent.com/u/37554840?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebtaher",
      "html_url": "https://github.com/zohebtaher",
      "followers_url": "https://api.github.com/users/zohebtaher/followers",
      "following_url": "https://api.github.com/users/zohebtaher/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebtaher/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebtaher/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebtaher/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebtaher/orgs",
      "repos_url": "https://api.github.com/users/zohebtaher/repos",
      "events_url": "https://api.github.com/users/zohebtaher/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebtaher/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebs341",
      "id": 62261716,
      "node_id": "MDQ6VXNlcjYyMjYxNzE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/62261716?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebs341",
      "html_url": "https://github.com/zohebs341",
      "followers_url": "https://api.github.com/users/zohebs341/followers",
      "following_url": "https://api.github.com/users/zohebs341/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebs341/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebs341/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebs341/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebs341/orgs",
      "repos_url": "https://api.github.com/users/zohebs341/repos",
      "events_url": "https://api.github.com/users/zohebs341/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebs341/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebAhmeDev",
      "id": 92684329,
      "node_id": "U_kgDOBYZAKQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/92684329?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebAhmeDev",
      "html_url": "https://github.com/ZohebAhmeDev",
      "followers_url": "https://api.github.com/users/ZohebAhmeDev/followers",
      "following_url": "https://api.github.com/users/ZohebAhmeDev/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebAhmeDev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebAhmeDev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebAhmeDev/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebAhmeDev/orgs",
      "repos_url": "https://api.github.com/users/ZohebAhmeDev/repos",
      "events_url": "https://api.github.com/users/ZohebAhmeDev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebAhmeDev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "trickster-5",
      "id": 90335734,
      "node_id": "MDQ6VXNlcjkwMzM1NzM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/90335734?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/trickster-5",
      "html_url": "https://github.com/trickster-5",
      "followers_url": "https://api.github.com/users/trickster-5/followers",
      "following_url": "https://api.github.com/users/trickster-5/following{/other_user}",
      "gists_url": "https://api.github.com/users/trickster-5/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/trickster-5/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/trickster-5/subscriptions",
      "organizations_url": "https://api.github.com/users/trickster-5/orgs",
      "repos_url": "https://api.github.com/users/trickster-5/repos",
      "events_url": "https://api.github.com/users/trickster-5/events{/privacy}",
      "received_events_url": "https://api.github.com/users/trickster-5/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ZohebShariffi",
      "id": 35684692,
      "node_id": "MDQ6VXNlcjM1Njg0Njky",
      "avatar_url": "https://avatars.githubusercontent.com/u/35684692?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZohebShariffi",
      "html_url": "https://github.com/ZohebShariffi",
      "followers_url": "https://api.github.com/users/ZohebShariffi/followers",
      "following_url": "https://api.github.com/users/ZohebShariffi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZohebShariffi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZohebShariffi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZohebShariffi/subscriptions",
      "organizations_url": "https://api.github.com/users/ZohebShariffi/orgs",
      "repos_url": "https://api.github.com/users/ZohebShariffi/repos",
      "events_url": "https://api.github.com/users/ZohebShariffi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZohebShariffi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebys",
      "id": 19163231,
      "node_id": "MDQ6VXNlcjE5MTYzMjMx",
      "avatar_url": "https://avatars.githubusercontent.com/u/19163231?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebys",
      "html_url": "https://github.com/zohebys",
      "followers_url": "https://api.github.com/users/zohebys/followers",
      "following_url": "https://api.github.com/users/zohebys/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebys/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebys/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebys/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebys/orgs",
      "repos_url": "https://api.github.com/users/zohebys/repos",
      "events_url": "https://api.github.com/users/zohebys/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebys/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebsarwar82",
      "id": 58395751,
      "node_id": "MDQ6VXNlcjU4Mzk1NzUx",
      "avatar_url": "https://avatars.githubusercontent.com/u/58395751?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebsarwar82",
      "html_url": "https://github.com/zohebsarwar82",
      "followers_url": "https://api.github.com/users/zohebsarwar82/followers",
      "following_url": "https://api.github.com/users/zohebsarwar82/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebsarwar82/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebsarwar82/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebsarwar82/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebsarwar82/orgs",
      "repos_url": "https://api.github.com/users/zohebsarwar82/repos",
      "events_url": "https://api.github.com/users/zohebsarwar82/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebsarwar82/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Zohebzak",
      "id": 112998680,
      "node_id": "U_kgDOBrw5GA",
      "avatar_url": "https://avatars.githubusercontent.com/u/112998680?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Zohebzak",
      "html_url": "https://github.com/Zohebzak",
      "followers_url": "https://api.github.com/users/Zohebzak/followers",
      "following_url": "https://api.github.com/users/Zohebzak/following{/other_user}",
      "gists_url": "https://api.github.com/users/Zohebzak/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Zohebzak/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Zohebzak/subscriptions",
      "organizations_url": "https://api.github.com/users/Zohebzak/orgs",
      "repos_url": "https://api.github.com/users/Zohebzak/repos",
      "events_url": "https://api.github.com/users/Zohebzak/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Zohebzak/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "rahiman-zoheb",
      "id": 11263019,
      "node_id": "MDQ6VXNlcjExMjYzMDE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/11263019?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rahiman-zoheb",
      "html_url": "https://github.com/rahiman-zoheb",
      "followers_url": "https://api.github.com/users/rahiman-zoheb/followers",
      "following_url": "https://api.github.com/users/rahiman-zoheb/following{/other_user}",
      "gists_url": "https://api.github.com/users/rahiman-zoheb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rahiman-zoheb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rahiman-zoheb/subscriptions",
      "organizations_url": "https://api.github.com/users/rahiman-zoheb/orgs",
      "repos_url": "https://api.github.com/users/rahiman-zoheb/repos",
      "events_url": "https://api.github.com/users/rahiman-zoheb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rahiman-zoheb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zoheb799",
      "id": 96819670,
      "node_id": "U_kgDOBcVZ1g",
      "avatar_url": "https://avatars.githubusercontent.com/u/96819670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zoheb799",
      "html_url": "https://github.com/zoheb799",
      "followers_url": "https://api.github.com/users/zoheb799/followers",
      "following_url": "https://api.github.com/users/zoheb799/following{/other_user}",
      "gists_url": "https://api.github.com/users/zoheb799/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zoheb799/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zoheb799/subscriptions",
      "organizations_url": "https://api.github.com/users/zoheb799/orgs",
      "repos_url": "https://api.github.com/users/zoheb799/repos",
      "events_url": "https://api.github.com/users/zoheb799/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zoheb799/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "infmz",
      "id": 7046054,
      "node_id": "MDQ6VXNlcjcwNDYwNTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7046054?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/infmz",
      "html_url": "https://github.com/infmz",
      "followers_url": "https://api.github.com/users/infmz/followers",
      "following_url": "https://api.github.com/users/infmz/following{/other_user}",
      "gists_url": "https://api.github.com/users/infmz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/infmz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/infmz/subscriptions",
      "organizations_url": "https://api.github.com/users/infmz/orgs",
      "repos_url": "https://api.github.com/users/infmz/repos",
      "events_url": "https://api.github.com/users/infmz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/infmz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebk",
      "id": 1052581,
      "node_id": "MDQ6VXNlcjEwNTI1ODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1052581?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebk",
      "html_url": "https://github.com/zohebk",
      "followers_url": "https://api.github.com/users/zohebk/followers",
      "following_url": "https://api.github.com/users/zohebk/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebk/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebk/orgs",
      "repos_url": "https://api.github.com/users/zohebk/repos",
      "events_url": "https://api.github.com/users/zohebk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebk/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zdhuka",
      "id": 3692846,
      "node_id": "MDQ6VXNlcjM2OTI4NDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3692846?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zdhuka",
      "html_url": "https://github.com/zdhuka",
      "followers_url": "https://api.github.com/users/zdhuka/followers",
      "following_url": "https://api.github.com/users/zdhuka/following{/other_user}",
      "gists_url": "https://api.github.com/users/zdhuka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zdhuka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zdhuka/subscriptions",
      "organizations_url": "https://api.github.com/users/zdhuka/orgs",
      "repos_url": "https://api.github.com/users/zdhuka/repos",
      "events_url": "https://api.github.com/users/zdhuka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zdhuka/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "zohebcore",
      "id": 22320462,
      "node_id": "MDQ6VXNlcjIyMzIwNDYy",
      "avatar_url": "https://avatars.githubusercontent.com/u/22320462?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zohebcore",
      "html_url": "https://github.com/zohebcore",
      "followers_url": "https://api.github.com/users/zohebcore/followers",
      "following_url": "https://api.github.com/users/zohebcore/following{/other_user}",
      "gists_url": "https://api.github.com/users/zohebcore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zohebcore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zohebcore/subscriptions",
      "organizations_url": "https://api.github.com/users/zohebcore/orgs",
      "repos_url": "https://api.github.com/users/zohebcore/repos",
      "events_url": "https://api.github.com/users/zohebcore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zohebcore/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]

  console.log(data[1].login)
  
  return (
    <>
    <Search/>
    <div className="container">
      {
        data.map(item => {
          return <User profile={item.url} name={item.login} imageUrl={item.avatar_url}/>
        })
      }
    </div>
    </>
  );
}

export default App;
